---
title: "Linear Models"
author: "Saryu Patel"
date: "11/14/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Import Data

```{r}
data("nyc_airbnb")

nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location/2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood
    ) %>% 
  filter(borough != "Staten Island") %>% 
  select(price, stars, borough, neighborhood, room_type)
```

## Fit a Model

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit <- lm(price ~ stars + borough, data = nyc_airbnb)
```

Look at the results.

```{r include=FALSE}
fit

summary(fit)
summary(fit)$coef
coef(fit)
residuals(fit)
```

Tidy up the results.

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
  ) %>% 
  knitr::kable(digits = 3)
```

## Be in control of factors

```{r}
nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(borough = fct_infreq(borough),
         room_type = fct_infreq(room_type))
```

Look at the plot again.

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) +
  geom_point()
```

```{r}
fit <- lm(price ~ stars + borough, data = nyc_airbnb)

broom::tidy(fit)
broom::glance(fit)
```

## Diagnostics

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
    ggplot(aes(x = borough, y = resid)) + 
    geom_violin() +
    ylim(-500, 1500)

nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) +
  geom_point() +
  facet_wrap(. ~ borough)
```

## Hypothesis Tests

This does t-tests by default.

```{r}
fit %>% 
  broom::tidy()
```

What about the significance of `borough`?

```{r}
fit_null <- lm(price ~ stars, data = nyc_airbnb)
fit_alt <- lm(price ~ stars + borough, data = nyc_airbnb)

anova(fit_null, fit_alt) %>% 
  broom::tidy()
```

## Nest Data, Fit Models

This is formal and complex.

```{r}
fit <- lm(price ~ stars * borough + room_type * borough, data = nyc_airbnb)

broom::tidy(fit)
```

This is more exploratory and easier to understand.

```{r}
nyc_airbnb %>% 
  nest(data = -borough) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(term == "stars")
```

```{r}
nyc_airbnb %>% 
  nest(data = -borough) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(term != "(Intercept)") %>% 
  select(borough, term, estimate) %>% 
  pivot_wider(
    names_from = borough,
    values_from = estimate
  )
```

Nest even more.

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan") %>%
  nest(data = -neighborhood) %>% 
  mutate(
    models = map(data, ~lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)
  ) %>% 
  select(-data, -models) %>% 
  unnest(results) %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() +
  facet_wrap(. ~ term) +
  theme(axis.text.x = element_text(angle = 70, hjust = 1))
```